#' Batch Evaluate
#'
#' @param mat A Numeric matrix or list of matrices after pre-processing and/or batch correction with features as rownames and sample names as the column names.
#' @param meta Data frame of sample data with the first column being sample names that match the column names of the matrix.
#' @param evaluation_method A character vector of batch correction methods in c("pca", "cluster_analysis", "mc_pca", "pca_details", "rle", "ev", "sva", "umap").
#' @param batch.1 Column name from the meta file of the column that will be used for batch information.
#' @param annotation Used by evaluation pca to select whether a cluster or meta annotated PCA plot is generated. cluster = "cluster", meta = "meta", all = c("cluster", "meta").
#' @param cluster_number Used by evaluation pca and evaluation cluster HE to select the number of kmeans generated clusters to display in the plot. If NULL is selected, a Silhouette generated cluster number is used.
#' @param variable_of_interest Column name from the meta file of the column that will be used for the variable of interest information
#' @param cluster_analysis_method Used by evaluation cluster analysis to select cluster analysis method. Elbow = "wss", Silhouette = "silhouette", Dunn = "dunn', all generates plots from each method.
#' @param color_by Used by evaluation multiple components, pca, and rle to select which feature will be used to color the individuals. Choices are "batch", "variable_of_interest", and "all". Default is set to "all".
#' @param ncomponents Used by evaluation multiple components to select the number of principal components that will be plotted. Default is set to 5.
#' @param pca_factors Used by evaluation pca details to select the Column name from the meta file of the column that will be used to group the summary details of the PCA plot. If NULL, batch is selected.
#' @param variable_choices Used by evaluation explanatory variables to select which variables to plot. Default is a combination of the batch and variable of interest.
#' @param sva_nsv_method Used by evaluation SVA to generate surrogate variables. Choices are "be" and "leek". Default is set to "be".
#' @param plot_title A list of titles for each matrix submitted. Used to named the plots generated by the batch evaluate function. Default will generate titles based on the uncorrected and corrected matrices.
#' @param topN A positive integer indicating the top number of genes to select based on variance. Default is set to 2000.
#' @param cluster_method The cluster method used by hclust. Default is set to ward.D2. Choices are "ward.D2", "ward.D", "complete", "single", "average", "mccquitty", "median", or "centroid".
#' @param var_type The variance measure used to select the top genes based on variance. Default is set to MAD. Choices are "MAD", "CV", or "VAR".
#' @param fill_percentage A TRUE/FALSE statement that determines if the y axis on the barplot will be a percentage or count. Default is set to TRUE
#' @param topN_pvca A positive integer indicating the top number of genes to select based on variance for PVCA. Default is set to 20000.
#' @param pvca_pct A numeric between 0 and 1 that indicates the percentile value of the minimum amount of the variabilities that the selected principal components need to explain. Default is set to 0.8.
#'
#' @return A list object separated by Plots and Matrices containing all plots and matrices generated by the selected evaluation methods
#' @export
#'
#' @examples
#' set.seed(333)
batch_evaluate = function(mat = NULL,
                          meta = NULL,
                          evaluation_method = "all",
                          batch.1 = NULL,
                          annotation = "all",
                          cluster_number = NULL,
                          variable_of_interest = NULL,
                          cluster_analysis_method = "all",
                          color_by = "all",
                          ncomponents = 5,
                          pca_factors = NULL,
                          variable_choices = NULL,
                          sva_nsv_method = "be",
                          plot_title = NULL,
                          topN = 2000,
                          var_type = "MAD",
                          cluster_method = "ward.D2",
                          fill_percentage = TRUE,
                          heatmap_annotation = NULL,
                          heatmap_rownames = FALSE,
                          heatmap_colnames = FALSE,
                          topN_pvca = 20000,
                          pvca_pct = 0.8){
  batch_evaluation_list <- list()
  if (is.null(mat)){
    stop("Please provide a matrix file or use retrieve_data or generate_data to generate a matrix file for batch_evaluate")
  }
  if (!all(apply(mat,2,is.numeric)) | !is(mat,"matrix")) stop("Must be numeric matrix")
  if (is.null(meta)){
    stop("please provide a meta file or use retrieve_data or generate_data to generate a meta file")
  }
  if (is.null(batch.1) & !"sva" %in% evaluation_method){
    stop("Please select column name in the meta file for the batch information")
  }
  if (is.null(variable_of_interest)){
    message("Missing variable of interest. Some correction methods and evaluation techniques are not available.")
  }
  if ("all" %in% evaluation_method) {
    evaluation_method = c("pca", "cluster_analysis", "cluster_HE", "mc_pca", "pca_details", "rle", "ev", "sva", "umap", "heatmap", "pvca")}
  if (is.null(variable_of_interest)) {
    evaluation_method = evaluation_method[evaluation_method != "sva"]}
  if (!all(evaluation_method %in% c("pca", "cluster_analysis", "cluster_HE", "mc_pca", "pca_details", "rle", "ev", "sva", "umap", "heatmap", "pvca"))) {
    stop("Evaluation correction method not found")}
  if ("all" %in% color_by){
    color_by = c("batch", "variable_of_interest", "BnW")
  }
  if (is.null(variable_of_interest)){
    color_by = color_by[color_by != "variable_of_interest"]
  }

  if ("pca" %in% evaluation_method){
    cat("\tConducting principal component analysis\n")
    batch_evaluation_list$Plots$pca <-  evaluation_pca(mat,
                                                       meta,
                                                       annotation,
                                                       cluster_number,
                                                       batch.1,
                                                       variable_of_interest,
                                                       color_by,
                                                       plot_title)
  }
  if ("cluster_analysis" %in% evaluation_method){
    cat("\tConducting cluster analysis\n")
    batch_evaluation_list$Plots$cluster_analysis <- evaluation_cluster_analysis(mat,
                                                                                cluster_analysis_method,
                                                                                plot_title)
  }
  if ("mc_pca" %in% evaluation_method){
    cat("\tConducting multiple components PCA analysis\n")
    batch_evaluation_list$Plots$mc_pca <- evaluation_mc_pca(mat,
                                                            meta,
                                                            batch.1,
                                                            variable_of_interest,
                                                            ncomponents,
                                                            color_by,
                                                            plot_title)
  }
  if ("pca_details" %in% evaluation_method){
    cat("\tConducting PCA details analysis\n")
    evaluation_pca_details_list <- evaluation_pca_details(mat,
                                                          meta,
                                                          batch.1,
                                                          pca_factors,
                                                          plot_title)
    batch_evaluation_list$Plots$pca_details <- evaluation_pca_details_list$Plots
    batch_evaluation_list$Matrices$pca_details <- evaluation_pca_details_list$Matrices
  }
  if ("rle" %in% evaluation_method){
    cat("\tConducting relative log expression analysis\n")
    batch_evaluation_list$Plots$rle <- evaluation_rle(mat,
                                                      meta,
                                                      batch.1,
                                                      variable_of_interest,
                                                      color_by,
                                                      plot_title)
  }
  if ("ev" %in% evaluation_method){
    cat("\tConducting explanatory variables analysis\n")
    batch_evaluation_list$Plots$ev <- evaluation_ev(mat,
                                                    meta,
                                                    variable_choices,
                                                    batch.1,
                                                    variable_of_interest,
                                                    plot_title)
  }
  if ("sva" %in% evaluation_method){
    cat("\tConducting surrogate variable analysis\n")
    evaluation_sva_list <- evaluation_sva(mat,
                                          meta,
                                          variable_of_interest,
                                          sva_nsv_method,
                                          plot_title)
    batch_evaluation_list$Plots$sva <- evaluation_sva_list$Plots
    batch_evaluation_list$Matrices$sva <- evaluation_sva_list$Matrices
  }
  if ("umap" %in% evaluation_method){
    cat("\tConducting uniform manifold approimation and projection analysis\n")
    batch_evaluation_list$Plots$umap <- evaluation_umap(mat,
                                                        meta,
                                                        batch.1,
                                                        variable_of_interest,
                                                        color_by,
                                                        plot_title)
  }
  if ("cluster_HE" %in% evaluation_method){
    cat("\tConducting heterogeneity and evenness cluster analysis\n")
    evluation_cluster_HE_list <- evaluation_cluster_HE(mat,
                                                       meta,
                                                       batch.1,
                                                       cluster_number,
                                                       topN,
                                                       cluster_method,
                                                       var_type,
                                                       fill_percentage,
                                                       plot_title)
    batch_evaluation_list$Plots$cluster_HE <- evluation_cluster_HE_list$Plots
    batch_evaluation_list$Matrices$cluster_HE <- evluation_cluster_HE_list$Matrices
  }
  if ("heatmap" %in% evaluation_method){
    cat("\tConducting heatmap analysis\n")
    batch_evaluation_list$Plots$heatmap <- evaluation_heatmap(mat,
                                                              meta,
                                                              batch.1,
                                                              variable_of_interest,
                                                              topN,
                                                              cluster_method,
                                                              var_type,
                                                              heatmap_annotation,
                                                              heatmap_rownames,
                                                              heatmap_colnames,
                                                              plot_title)
  }
  if ("pvca" %in% evaluation_method){
    cat("\tConducting principal variance component analysis analysis\n")
    batch_evaluation_list$Plots$pvca <- evaluation_pvca(mat,
                                                        meta,
                                                        batch.1,
                                                        variable_of_interest,
                                                        topN_pvca,
                                                        var_type,
                                                        variable_choices,
                                                        pvca_pct,
                                                        plot_title)
  }
  return(batch_evaluation_list)
}
